#!/usr/bin/env python3
"""Generate vectors.json -- the shared conformance corpus.

Every implementation encodes each tree and must produce the listed bytes, then
decodes those bytes and must recover the tree. Two implementations that agree
with a third-party file cannot quietly agree with each other on something the
grammar does not say.

Trees and bytes are hex-encoded so the file stays plain ASCII and diffs
readably.

Run:  python3 make_vectors.py > vectors.json

Copyright (c) 2026 M. A. Chatterjee, BSD-2-Clause.
"""

import json
import pathlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from terseml import Element, encode  # noqa: E402


def T(tag, attrs=(), kids=()):
    return Element(tag, list(attrs), list(kids))


CASES = [
    # name, tree
    ("text-plain", T(b"p", [], [b"hello"])),
    ("text-commas", T(b"p", [], [b"a,b,c"])),
    ("text-brackets", T(b"p", [], [b"see [[link]]"])),
    ("text-leading-bracket", T(b"p", [], [b"[start]"])),
    ("text-braces", T(b"p", [], [b"use {{t}}"])),
    ("text-backslash", T(b"p", [], [b"back\\slash"])),
    ("empty-content", T(b"p", [], [])),
    ("singleton", T(b"#text", [], [b"bare"])),
    ("attrs-one", T(b"a", [(b"href", b"/x")], [b"click"])),
    ("attrs-many", T(b"a", [(b"k", b"v"), (b"j", b"w")], [b"t"])),
    ("attrs-reserved", T(b"a", [(b"k:1", b"v,2")], [b"t"])),
    ("attrs-no-content", T(b"img", [(b"src", b"/i.png")], [])),
    ("nested", T(b"div", [], [T(b"b", [], [b"bold"])])),
    ("mixed-content", T(b"p", [], [b"Hello ", T(b"b", [], [b"world"]), b"!"])),
    ("repeated-siblings", T(b"l", [], [T(b"i", [], [b"a"]), T(b"i", [], [b"b"])])),
    ("deep", T(b"a", [], [T(b"b", [], [T(b"c", [], [T(b"d", [], [b"x"])])])])),
    ("tag-reserved", T(b"t,g", [], [b"x"])),
    ("tag-brace", T(b"t{g", [], [b"x"])),
    ("bytes-all-256", T(b"bin", [], [bytes(range(256))])),
    ("bytes-nul", T(b"bin", [], [b"a\x00b"])),
    ("bytes-high", T(b"bin", [], [b"\xff\xfe\xfd"])),
    # binary run selection -- one per form, per GRAMMAR §5.1
    ("form-inline-ascii", T(b"d", [], [b"a" * 600])),
    ("form-counted-random", T(b"d", [], [bytes((i * 37 + 11) % 256 for i in range(600))])),
    ("form-terminated-braces", T(b"d", [], [b"{}" * 300])),
    ("form-counted-nuls", T(b"d", [], [bytes(600)])),
    ("form-boundary-short", T(b"d", [], [bytes((i * 37) % 256 for i in range(16))])),
]


def node_json(n):
    if isinstance(n, Element):
        return {
            "tag": n.tag.hex(),
            "attrs": [[k.hex(), v.hex()] for k, v in n.attrs],
            "children": [node_json(c) for c in n.children],
        }
    return {"text": bytes(n).hex()}


def emit_header(cases, path):
    """A C header of the same corpus. Parsing JSON in C to run a conformance
    test would be a second thing to get wrong."""
    lines = [
        "/* Generated by make_vectors.py -- do not edit. */",
        "#ifndef TERSEML_VECTORS_H",
        "#define TERSEML_VECTORS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    const uint8_t *wire;",
        "    size_t len;",
        "} tsml_vector;",
        "",
    ]
    for i, c in enumerate(cases):
        raw = bytes.fromhex(c["wire"])
        body = ", ".join(f"0x{b:02x}" for b in raw)
        lines.append(f"static const uint8_t tsml_wire_{i}[] = {{{body}}};")
    lines += ["", "static const tsml_vector TSML_VECTORS[] = {"]
    for i, c in enumerate(cases):
        n = len(bytes.fromhex(c["wire"]))
        lines.append(f'    {{"{c["name"]}", tsml_wire_{i}, {n}}},')
    lines += ["};", "",
              "#define TSML_VECTOR_COUNT (sizeof(TSML_VECTORS) / sizeof(TSML_VECTORS[0]))",
              "", "#endif", ""]
    pathlib.Path(path).write_text("\n".join(lines))


def main():
    out = {
        "note": "Shared conformance vectors for terseml. See GRAMMAR.md.",
        "cases": [
            {"name": name, "tree": node_json(tree), "wire": encode(tree).hex()}
            for name, tree in CASES
        ],
    }
    emit_header(out["cases"], os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                           "vectors.h"))
    json.dump(out, sys.stdout, indent=1)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
