#!/usr/bin/env bash
#
# sync_version.sh — propagate the version in triepack-version.txt into every
# file that carries a user-visible version string. Idempotent: running it when
# everything already matches is a no-op.
#
# Single source of truth: triepack-version.txt   ("X.Y.Z", one line)
#
# To bump the version:
#   1. Edit triepack-version.txt
#   2. Run ./scripts/sync_version.sh
#
# Files kept in sync:
#   bindings/javascript/package.json        npm version
#   bindings/typescript/package.json        in-repo wrapper version (not published)
#   bindings/python/pyproject.toml          PyPI version
#   bindings/python/triepack/__init__.py    __version__
#   bindings/python/tests/test_triepack.py  the __version__ assertion
#   bindings/rust/Cargo.toml                crate version
#   bindings/java/build.gradle              Gradle version
#   bindings/kotlin/build.gradle.kts        Gradle version
#   the VERSION constant each binding reports through version():
#     bindings/javascript/src/index.js      bindings/go/triepack.go
#     bindings/rust/src/lib.rs              bindings/swift/.../Triepack.swift
#     bindings/java/.../TriePack.java       bindings/kotlin/.../TriePack.kt
#   docs/_config.yml                        version shown in the site header
#   README.md                               title line
#   terseml/terseml.{h,py,js}               TSML_VERSION / __version__ / VERSION
#     terseml is a subproject, not a component. It tracks this version while it
#     lives here; spinning it out means deleting those three entries.
#
# Derived automatically, so not listed above and never edited by hand:
#   CMakeLists.txt        reads triepack-version.txt directly
#   triepack_version.h    generated by CMake (TP_VERSION_STRING)
#   tools/trp_inspect.c   prints TP_VERSION_STRING
#
# NOT touched: TP_VERSION_MAJOR / TP_VERSION_MINOR in the encoders. Those are
# the on-disk *format* version and move independently of the release version.
#
# Usage:
#   ./scripts/sync_version.sh              # sync every file
#   ./scripts/sync_version.sh --check      # verify only, exit 1 on drift
#
# Exit status: 0 in sync (or successfully synced), 1 on drift in --check mode,
#              2 on usage error.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

if [[ -t 1 ]]; then
    GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
else
    GREEN=''; YELLOW=''; RED=''; NC=''
fi

MODE="sync"
for arg in "$@"; do
    case "$arg" in
        --check) MODE="check" ;;
        -h|--help)
            sed -n '3,41p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown argument: ${arg}${NC}" >&2
            echo "Try $0 --help" >&2
            exit 2
            ;;
    esac
done

# --------------------------------------------------------------------------
# Source of truth
# --------------------------------------------------------------------------
VER_FILE="${PROJECT_ROOT}/triepack-version.txt"
if [[ ! -f "${VER_FILE}" ]]; then
    echo -e "${RED}triepack-version.txt not found${NC}" >&2
    exit 2
fi

VERSION=$(head -1 "${VER_FILE}" | tr -d '[:space:]')
if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo -e "${RED}triepack-version.txt must hold a bare X.Y.Z version, got '${VERSION}'${NC}" >&2
    exit 2
fi

echo -e "Source of truth: ${GREEN}triepack-version.txt${NC}  →  ${GREEN}${VERSION}${NC}"
echo ""

DRIFT=0
CHANGED=0

# --------------------------------------------------------------------------
# Apply a perl -i substitution, diffing against a snapshot to spot real change.
# Args: label, file, perl expression
# --------------------------------------------------------------------------
update_file() {
    local label="$1" file="$2" perl_expr="$3"

    if [[ ! -f "${file}" ]]; then
        echo -e "  ${YELLOW}skip${NC}    ${label} (${file} not found)"
        return
    fi

    cp "${file}" "${file}.prev"
    perl -i -pe "${perl_expr}" "${file}"

    if cmp -s "${file}" "${file}.prev"; then
        echo -e "  ${GREEN}ok${NC}      ${label}"
        rm -f "${file}.prev"
    elif [[ "${MODE}" == "check" ]]; then
        mv "${file}.prev" "${file}"
        echo -e "  ${RED}DRIFT${NC}   ${label}"
        DRIFT=1
    else
        echo -e "  ${YELLOW}updated${NC} ${label}"
        rm -f "${file}.prev"
        CHANGED=1
    fi
}

SEMVER='[0-9]+\.[0-9]+\.[0-9]+'

# --------------------------------------------------------------------------
# npm packages — the first "version" key, which is the package's own.
# --------------------------------------------------------------------------
update_file "bindings/javascript/package.json" "bindings/javascript/package.json" \
    "s|(\"version\":\\s*\")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/typescript/package.json" "bindings/typescript/package.json" \
    "s|(\"version\":\\s*\")${SEMVER}(\")|\${1}${VERSION}\${2}|"

# --------------------------------------------------------------------------
# Python
# --------------------------------------------------------------------------
update_file "bindings/python/pyproject.toml" "bindings/python/pyproject.toml" \
    "s|^(version = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/python/triepack/__init__.py" "bindings/python/triepack/__init__.py" \
    "s|^(__version__ = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/python/tests/test_triepack.py version assertion" \
    "bindings/python/tests/test_triepack.py" \
    "s|(triepack\\.__version__ == \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

# --------------------------------------------------------------------------
# Rust — the [package] version, which is the first one in the file.
# --------------------------------------------------------------------------
update_file "bindings/rust/Cargo.toml" "bindings/rust/Cargo.toml" \
    "s|^(version = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

# --------------------------------------------------------------------------
# JVM
# --------------------------------------------------------------------------
update_file "bindings/java/build.gradle" "bindings/java/build.gradle" \
    "s|^(version = ')${SEMVER}(')|\${1}${VERSION}\${2}|"

update_file "bindings/kotlin/build.gradle.kts" "bindings/kotlin/build.gradle.kts" \
    "s|^(version = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/javascript src/index.js VERSION" \
    "bindings/javascript/src/index.js" \
    "s|(const VERSION = ')${SEMVER}(')|\${1}${VERSION}\${2}|"

update_file "bindings/go triepack.go Version" \
    "bindings/go/triepack.go" \
    "s|(const Version = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/rust src/lib.rs VERSION" \
    "bindings/rust/src/lib.rs" \
    "s|(pub const VERSION: &str = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/swift Triepack.swift version" \
    "bindings/swift/Sources/Triepack/Triepack.swift" \
    "s|(public static let version = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/java TriePack.java VERSION" \
    "bindings/java/src/main/java/com/deftio/triepack/TriePack.java" \
    "s|(public static final String VERSION = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "bindings/kotlin TriePack.kt VERSION" \
    "bindings/kotlin/src/main/kotlin/com/deftio/triepack/TriePack.kt" \
    "s|(const val VERSION = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

# --------------------------------------------------------------------------
# terseml -- a subproject in this repository, not a TriePack component. It
# tracks this version for now because one number across one repository is less
# confusing than two; when it is spun out it will version independently and
# these three lines come out of this script.
# --------------------------------------------------------------------------
update_file "terseml/terseml.h TSML_VERSION" "terseml/terseml.h" \
    "s|(#define TSML_VERSION \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "terseml/terseml.py __version__" "terseml/terseml.py" \
    "s|^(__version__ = \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "terseml/terseml.js VERSION" "terseml/terseml.js" \
    "s|(const VERSION = ')${SEMVER}(')|\${1}${VERSION}\${2}|"

# --------------------------------------------------------------------------
# Docs site and README
# --------------------------------------------------------------------------
update_file "docs/_config.yml" "docs/_config.yml" \
    "s|^(version: \")${SEMVER}(\")|\${1}${VERSION}\${2}|"

update_file "README.md title" "README.md" \
    "s|^(# triepack v)${SEMVER}|\${1}${VERSION}|"

# --------------------------------------------------------------------------
# CMake reads the file directly, so only confirm the wiring is still there.
# --------------------------------------------------------------------------
if grep -q 'triepack-version.txt' CMakeLists.txt; then
    echo -e "  ${GREEN}ok${NC}      CMakeLists.txt (reads triepack-version.txt)"
else
    echo -e "  ${RED}DRIFT${NC}   CMakeLists.txt no longer reads triepack-version.txt"
    DRIFT=1
fi

echo ""
if [[ "${MODE}" == "check" ]]; then
    if [[ ${DRIFT} -ne 0 ]]; then
        echo -e "${RED}Version drift detected.${NC} Run ./scripts/sync_version.sh and commit the result." >&2
        exit 1
    fi
    echo -e "${GREEN}All version strings match ${VERSION}.${NC}"
else
    if [[ ${CHANGED} -ne 0 ]]; then
        echo -e "${GREEN}Synced to ${VERSION}.${NC} Review with 'git diff' and commit."
    else
        echo -e "${GREEN}Already at ${VERSION}; nothing to do.${NC}"
    fi
fi
